### ISSUE TITLE
add organization profile

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/.github#1]
Go to https://github.com/DeCenter-AI/.github

![Image](https://github.com/DeCenter-AI/.github/assets/24226219/b0957712-01a7-4960-ac5e-5fcb8fa5bf5e)

**Comment by VictorKaycee17** [comment]
Review the org Profile @Nasfame

**Comment by Nasfame** [comment]
@VictorKaycee17 gud u created a readme for the repo. Now to create a profile u need to : click on add readme

**Comment by VictorKaycee17** [comment]
Done
